# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_directory: '%kernel.project_dir%/public/uploads'
    frontend_url: '%env(FRONTEND_URL)%'
    s3_endpoint: '%env(S3_ENDPOINT)%'
    s3_access_key: '%env(S3_ACCESS_KEY)%'
    s3_secret_key: '%env(S3_SECRET_KEY)%'
    s3_bucket: '%env(S3_BUCKET)%'
    s3_region: '%env(S3_REGION)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Custom services configuration
    App\Service\NotificacionService:
        arguments:
            $frontendUrl: '%frontend_url%'

    App\Service\FileUploadService:
        arguments:
            $s3Endpoint: '%s3_endpoint%'
            $s3AccessKey: '%s3_access_key%'
            $s3SecretKey: '%s3_secret_key%'
            $s3Bucket: '%s3_bucket%'
            $s3Region: '%s3_region%'
            $uploadDir: '%upload_directory%'

    App\Service\QRCodeService:
        arguments:
            $frontendUrl: '%frontend_url%'
            $uploadDir: '%upload_directory%'
