framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'noreply@objetos-perdidos.local'
        headers:
            From: 'Portal Objetos Perdidos <noreply@objetos-perdidos.local>'
